local L = AceLibrary("AceLocale-2.2"):new("guildroll")

L:RegisterTranslations("enUS", function() return {
  --["Term"] = true, -- Example
  -- common
  ["Refresh"] = true,
  ["Refresh window"] = true,
  ["Clear"] = true,
  ["Name"] = true,
  ["Raid Only"] = true,
  ["Only show members in raid."] = true,
  ["Restarted"] = true,
  ["Minimum MainStanding: %s"] = "Minimum EP: %s",
  ["Minimum MainStanding"] = "Minimum EP",
  ["Set Minimum MainStanding"] = "Set Minimum EP",
  -- logs
  ["guildroll logs"] = true,
  ["Clear Logs."] = true,
  ["Time"] = true,
  ["Action"] = true,
  ["This will permanently delete all Admin Log entries. Continue?"] = true,
  -- loot
  ["guildroll loot info"] = true,
  ["Clear Loot."] = true,
  ["Item"] = true,
  ["Binds"] = true,
  ["Looter"] = true,
  ["AuxStanding Action"] = "EP Action",
  -- migrations
  ["Updated %d members to v3 storage."] = true,
  ["Countdown"] = true,
  ["Rank"] = true,
  ["OnAlt"] = true,
  -- standings
  ["Ctrl-C to copy. Esc to close."] = true,
  ["Ctrl-V to paste data. Esc to close."] = true,
  ["Imported %d members."] = true,
  ["Imported %d members.\n"] = true,
  ["%s\nFailed to import:"] = true,
  ["guildroll standings"] = true,
  ["Group by class"] = true,
  ["Group members by class."] = true,
  ["Export"] = true,
  ["Export standings to csv."] = true,
  ["Import"] = true,
  ["Import standings from csv."] = true,
  ["MainStanding"] = "EP",
  ["AuxStanding"] = "EP",
  ["RollValue"] = true,
  ["Standing"] = true,
  ["Main Standing"] = "EP",
  ["Auxiliary"] = "EP",
  ["Roll Value"] = "Roll",
  IMPORT_WARNING = [[Warning: 
Import overwrites all existing Standing values.

Paste all the csv data here replacing this text, 
then hit Import.
Results will print here when done.]],
  ["Group by armor"] = true,
  ["Group members by armor."] = true,
  ["Group by roles"] = true,
  ["Group members by roles."] = true,
  ["CLOTH"] = true,
  ["LEATHER"] = true,
  ["MAIL"] = true,
  ["PLATE"] = true,
  ["TANK"] = true,
  ["HEALER"] = true,
  ["CASTER"] = true,
  ["PHYS DPS"] = true,
  -- guildroll
  ["{guildroll}Type \"+\" if on main, or \"+<YourMainName>\" (without quotes) if on alt within %dsec."] = true,
  ["|cffFF3333|Hguildepbid:1:$ML|h[Mainspec/NEED]|h|r"] = true,
  ["Bids"] = true,
  ["Show Bids Table."] = true,
  ["ClearLoot"] = true,  
  ["Clear Loot Table."] = true,
  ["ClearLogs"] = true,  
  ["Clear Logs Table."] = true,
  ["Standings"] = true,  
  ["Show Standings Table."] = true,
  ["Restart"] = true,  
  ["Restart guildroll if having startup problems."] = true,
  ["v%s Loaded."] = true,  
  ["Alt Click/RClick/MClick"] = true,
  ["Manually modified %s\'s note. Standing was %s"] = true,
  ["|cffff0000Manually modified %s\'s note. Standing was %s|r"] = true,
  ["or $OS "] = true,
  ["$MS or "] = true,
  ["You have received a %d MainStanding penalty."] = "You have received a %d EP penalty.",
  ["You have been awarded %d MainStanding."] = "You have been awarded %d EP.",
  ["You have gained %d AuxStanding."] = "You have gained %d EP.",
  ["%s%% decay to Standing."] = true,
  ["%d MainStanding awarded to Raid."] = "%d EP awarded to Raid.",
  ["New %s version available: |cff00ff00%s|r"] = true,
  ["Visit %s to update."] = true,
  [", decay %"] = true,
  ["New decay %"] = true,
  [" settings accepted from %s"] = true,
  ["Giving %d MainStanding to all raidmembers"] = "Giving %d EP to all raidmembers",
  ["Giving %d AuxStanding to all raidmembers"] = "Giving %d EP to all raidmembers",
  ["You aren't in a raid dummy"] = true,
  ["Giving %d MainStanding to %s%s. (Previous: %d, New: %d)"] = "Giving %d EP to %s%s. (Previous: %d, New: %d)",
  ["Giving %d AuxStanding to %s%s. (Previous: %d, New: %d)"] = "Giving %d EP to %s%s. (Previous: %d, New: %d)",
  ["%s MainStanding Penalty to %s%s. (Previous: %d, New: %d)"] = "%s EP Penalty to %s%s. (Previous: %d, New: %d)",
  ["%s AuxStanding Penalty to %s%s. (Previous: %d, New: %d)"] = "%s EP Penalty to %s%s. (Previous: %d, New: %d)",  
  ["%s\'s officernote is broken:%q"] = true,
  ["All Standing decayed by %d%%"] = true,
  ["All Standing decayed by %s%%"] = true,
  ["DecayAnnounce"] = "[DECAY] All EP decayed by %s%%",
  ["All AuxStanding has been reset to %d."] = "All EP has been reset to %d.",
  ["All Standing has been reset to 0/%d."] = true,
  ["You now have: %d MainStanding %d AuxStanding + (%d)"] = "You now have: %d EP (Main), %d EP (Aux) + (%d)",
  ["Close to Standing Cap. Next Decay will change your |cffff7f00PR|r by |cffff0000%.4g|r."] = true,
  ["Hint:"] = true,
  ["|cffffff00Click|r to toggle Standings.%s \n|cffffff00Right-Click|r for Options."] =
    "Hint: |cffffff00Click|r to toggle Standings.%s \n|cffffff00Right-Click|r for Options.",
  [" \n|cffffff00Alt+Click|r to toggle Bids. \n|cffffff00Shift+Click|r to toggle Loot. \n|cffffff00Ctrl+Alt+Click|r to toggle Alts. \n|cffffff00Ctrl+Shift+Click|r to toggle Logs."] = " \n|cffffff00Alt+Click|r to toggle Alts. \n|cffffff00Ctrl+Click|r to toggle Logs. \n|cffffff00Shift+Click|r to toggle Roll UI.",
  [" \n|cffffff00Alt+Click|r to toggle Alts. \n|cffffff00Shift+Click|r to toggle Roll UI."] =
    " \n|cffffff00Alt+Click|r to toggle Alts. \n|cffffff00Shift+Click|r to toggle Roll UI.",
  [" \n|cffffff00Alt+Click|r to toggle Alts. \n|cffffff00Ctrl+Click|r to toggle Logs. \n|cffffff00Shift+Click|r to toggle Roll UI."] =
    " \n|cffffff00Alt+Click|r to toggle Alts. \n|cffffff00Ctrl+Click|r to toggle Logs. \n|cffffff00Shift+Click|r to toggle Roll UI.",
  ["Account MainStanding to %s."] = "Account EP to %s.",
  ["Account AuxStanding to %s."] = "Account EP to %s.", -- Internal use only (not GUI)
  -- Error messages and validation
  ["Invalid CSR input. Please enter a number between 0 and 15."] = true,
  ["Invalid EP value entered."] = true,
  ["EP value out of range (%s to %s)"] = true,
  ["You don't have permission to award EP."] = true,
  ["Invalid GP value entered."] = "Invalid EP value entered.",
  ["GP value out of range (%s to %s)"] = "EP value out of range (%s to %s)",
  -- StaticPopup prompts
  ["Enter EP to award to raid members:"] = true,
  ["GIVING_EP_MAIN_OF_ALT"] = "Giving EP to %s (main of %s); current EP: %d",
  ["GIVING_EP_TO_CHAR"] = "Giving EP to %s; current EP: %d",
  ["Enter number of weeks you SR this item (0..15):"] = true,
  ["guildroll options"] = true,
  ["+MainStanding to Member"] = "+EP to Member",
  ["Account MainStanding for member."] = "Account EP for member.",
  ["+MainStanding to Raid"] = "+EP to Raid",
  ["Award MainStanding to all raid members."] = "Award EP to all raid members.",
  ["Set Main"] = true,
  ["Set your Main Character."] = true,
  ["Raid Progress"] = true,
  ["Highest Tier the Guild is raiding.\nUsed to adjust suggested Standing rewards."] = true,
  ["4.Naxxramas"] = true,
  ["3.Temple of Ahn\'Qiraj"] = true,
  ["2.Blackwing Lair"] = true,
  ["1.Molten Core"] = true,
  ["Reporting channel"] = true,
  ["Channel used by reporting functions."] = true,
  ["Decay Standing"] = true,
  ["Decays all Standing by %s%%"] = true,
  ["Confirm Decay"] = true,
  ["Are you sure you want to decay all Standing by %s%%? This cannot be undone."] = true,
  ["Set Decay %"] = true,
  ["Set Decay percentage (Admin only)."] = true,
  ["Offspec Price %"] = true,
  ["Set Offspec Items EP Percent."] = true,
  ["Reset Standing"] = true,
  ["Reset AuxStanding"] = "Reset EP",
  ["Resets everyone\'s Standing to 0/%d (Admin only)."] = "Resets everyone\'s Standing to 0/%d (Admin only).",
  -- Added missing long confirmation string used in static popup:
  ["|cffff0000This will reset ALL player Standing to 0. This action cannot be undone!\n\nAre you ABSOLUTELY sure?|r"] = true,
  ["Resets everyone\'s AuxStanding to 0/%d (Admin only)."] = "Resets everyone\'s EP to 0/%d (Admin only).",
  ["Scanning %d members for Standing data. (%s)"] = true,
  ["^{guildroll}Type"] = true,
  ["Clearing old Bids"] = true,
  ["%s not found in the guild or not max level!"] = true,
  ["Molten Core"] = true,
  ["Onyxia\'s Lair"] = true,
  ["Blackwing Lair"] = true,
  ["Ahn\'Qiraj"] = true,
  ["Naxxramas"] = true,
  ["There are %d loot drops stored. It is recommended to clear loot info before a new raid. Do you want to clear it now?"] = true,
  ["Show me"] = true,
  ["Logs cleared"] = true,
  ["Loot info cleared"] = true,
  ["Loot info can be cleared at any time from the Tablet context menu or '/guildep clearloot' command"] = true,
  ["|cffff0000Are you sure you want to Reset ALL Standing?|r"] = true,
  ["|cffff0000This will reset ALL AuxStanding?|r"] = "|cffff0000This will reset ALL EP?|r", 
  ["AuxStanding Actions"] = "EP Actions",
  ["Remind me Later"] = true, 
  ["guildroll alts"] = true,
  ["Enable Alts"] = true,
  ["Main"] = true,
  ["Alt"] = true,
  ["Allow Alts to use Main\'s Standing."] = true,
  ["Alts MainStanding %"] = "Alts EP %",
  ["Set the % MainStanding Alts can earn."] = "Set the % EP Alts can earn.",
  [", alts"] = true,
  ["New Alts"] = true,
  [", alts MainStanding %"] = ", alts EP %",
  ["New Alts MainStanding %"] = "New Alts EP %",
  ["Manually modified %s\'s note. Previous main was %s"] = true,
  ["|cffff0000Manually modified %s\'s note. Previous main was %s|r"] = true,
  [", %s\'s Main."] = true,
  ["Your main has been set to %s"] = true,
  ["Alts"] = true,
  ["New Minimum MainStanding"] = "New Minimum EP",
  ["CSR Threshold"] = true,
  ["Maximum rank index allowed to view CSR"] = "Maximum rank index allowed to view CSR (0 = highest rank)",
  ["Show all Roll Buttons"] = "Show all Roll Buttons",
  -- Buff Checks
  ["Buff Checks"] = true,
  ["Admin buff verification tools"] = true,
  ["Check Buffs"] = true,
  ["Check raid-level buffs required (special paladin rule)."] = true,
  ["Check Consumes"] = true,
  ["Check raid consumes per-class and propose awarding EP."] = true,
  ["Check Flasks"] = true,
  ["Check raid flasks per-class."] = true,
  ["BuffCheck_NotInRaid"] = "You are not in a raid.",
  ["BuffCheck_AllOk"] = "All members have required buffs/consumables!",
  ["BuffCheck_Header"] = "Run a check to see results.",
  ["BuffCheck_PlayerMissing"] = "%s is missing %s",
  ["BuffCheck_PlayerMissingPaladin"] = "%s has %d/%d paladin blessings",
  ["BuffCheck_WhisperText"] = "Check completed",
  ["ConsumesCheck_AllOk"] = "All members have required consumables!",
  ["ConsumesCheck_Header"] = "Consumables Check Results",
  ["ConsumesCheck_PlayerMissing"] = "%s has %d/%d consumables",
  ["ConsumesCheck_ReadyToAward"] = "All members ready. Use +EP to Raid to award points.",
  ["FlasksCheck_AllOk"] = "All members have required flasks!",
  ["FlasksCheck_ReadyToAward"] = "All members ready. Use +EP to Raid to award points.",
  ["All members have required consumes. Award EP to raid?"] = true,
  ["All members have required flasks. Award EP to raid?"] = true,
  -- Menu reorganization
  ["Quick Actions"] = true,
  ["EP Actions"] = true,
  ["Options"] = true,
  ["Admin Settings"] = true,
  ["Admin configuration options"] = true,
  ["Toggle Roll Button"] = true,
  ["Show Standings"] = true,
  ["Show Personal Log"] = true,
  ["Show Alts"] = true,
  ["Show Admin Log"] = true,
  ["Toggle Alt pooling"] = true,
  ["Set Alts %"] = true,
  ["Set Min EP"] = true,
  ["Set Min EP (Current: %s)"] = true,
  ["Share Settings"] = true,
  ["Reset frames"] = true,
  ["Export/Import"] = true,
  ["Migrate Main Tags"] = true,
  ["Reset Standing"] = true,
  -- Standings improvements
  ["Give EP..."] = true,
  ["Award EP to this player"] = true,
  -- Personal log improvements
  ["Clear personal log"] = true,
  ["Clear your personal log"] = true,
  ["This will permanently delete your personal log. Continue?"] = true,
  ["Personal log cleared"] = true,
  -- Admin log improvements
  ["Last remote TS: %s"] = true,
  ["Snapshot in progress..."] = true,
  ["Request full sync"] = true,
  ["Request snapshot from peers"] = true,
  ["Never synced"] = true,
} end)
